// Auto-generated by stat.py
// Unit 044 Data
import type { UnitData } from '../../app/unit/types';

export const unit044Data: UnitData = {
  unitId: 44,
  coreData: {
    forms: [
    {
      formId: 0,
      name: "鬼にゃんま",
      stats: [2200, 3, 12, 1650, 20, 180, 2000, 555, 0, 320, 0, 0, 0, 28, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
    },
    {
      formId: 1,
      name: "鬼神にゃんま",
      stats: [2900, 3, 12, 2250, 20, 180, 2000, 555, 0, 320, 0, 0, 0, 28, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
    },
    {
      formId: 2,
      name: "獄炎鬼にゃんま",
      stats: [3900, 3, 12, 3750, 20, 180, 2000, 555, 0, 320, 0, 0, 0, 28, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
    }
    ],
    rarity: {
      id: 4,
      name: "超激レア",
      maxLevels: [60, 70]
    },
    levelRates: [20, 20, 20, 20, 20, 20, 10, 10, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
  },
  auxiliaryData: {
    names: ["鬼にゃんま", "鬼神にゃんま", "獄炎鬼にゃんま"],
    talents: {
      hasTalents: true,
      hasUltra: false,
      talentList: [
      {
        id: 10,
        name: "攻撃力アップ",
        type: "normal" as const,
        effect: "AP+20%/Lv Max+200% HP≦33% ->191,250 ->229,500",
        npCost: 235,
        isTotal: true
      },
      {
        id: 22,
        name: "波動ダメージ耐性",
        type: "normal" as const,
        effect: "+5%/Lv Max50%",
        npCost: 175,
        isTotal: true
      },
      {
        id: 32,
        name: "基本体力アップ",
        type: "normal" as const,
        effect: "+2%/Lv Max+20%",
        npCost: 175,
        isTotal: true
      },
      {
        id: 31,
        name: "基本攻撃力アップ",
        type: "normal" as const,
        effect: "+2%/Lv Max+20%",
        npCost: 175,
        isTotal: true
      },
      {
        id: 25,
        name: "生産コスト割引[円]",
        type: "normal" as const,
        effect: "-75/Lv Max-750",
        npCost: 175,
        isTotal: true
      }
      ]
    }
  }
} as const;

export default unit044Data;

