// Auto-generated by stat.py
// Unit 802 Data (level-independent)
import type { UnitData } from '../../app/unit/types';

export const unit802Data: UnitData = {
  unitId: 802,
  coreData: {
    forms: [
    {
      formId: 0,
      name: "802-1",
      stats: [100, 1, 0, 2700, 0, 800, 0, 0, 0, 320, 1, 0, 1, 41, 9, 9, 1, 1, 1, 1, 1, 1, 1, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, -1, 2, 0, 0, 0, 0, 1, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0],
      icon: "",
      animLength: 86
    }
    ],
    rarity: {
      id: 1,
      name: "EX",
      maxLevels: [50, 0]
    },
    levelRates: [20, 20, 20, 20, 20, 20, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
  },
  auxiliaryData: {
    names: ["802-1"],
    talents: {
      hasTalents: false,
      hasUltra: false,
      talentList: [

      ]
    }
  }
} as const;

export default unit802Data;

