// Auto-generated by stat.py
// Unit 770 Data (level-independent)
import type { UnitData } from '../../app/unit/types';

export const unit770Data: UnitData = {
  unitId: 770,
  coreData: {
    forms: [
    {
      formId: 0,
      name: "771-1",
      stats: [100, 1, 0, 2700, 0, 800, 0, 0, 0, 320, 1, 0, 1, 41, 9, 9, 1, 1, 1, 1, 1, 1, 1, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100, 150, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, -1, 2, 0, 0, 0, 0, 1, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0],
      icon: "",
      animLength: 86
    }
    ],
    rarity: {
      id: 4,
      name: "超激レア",
      maxLevels: [60, 0]
    },
    levelRates: [20, 20, 20, 20, 20, 20, 10, 10, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
  },
  auxiliaryData: {
    names: ["771-1"],
    talents: {
      hasTalents: false,
      hasUltra: false,
      talentList: [

      ]
    }
  }
} as const;

export default unit770Data;

