// Auto-generated by stat.py
// Unit 071 Data
import type { UnitData } from '../../app/unit/types';

export const unit071Data: UnitData = {
  unitId: 71,
  coreData: {
    forms: [
    {
      formId: 0,
      name: "真田幸村",
      stats: [850, 5, 65, 750, 0, 170, 2050, 900, 0, 320, 0, 0, 1, 1, 0, 9, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, -1, 0, 75, 0, 8, 0, 1, 1, 0, -1, 0, 0, 0]
    },
    {
      formId: 1,
      name: "武神・真田幸村",
      stats: [1700, 5, 65, 1500, 0, 170, 2050, 900, 0, 320, 0, 0, 1, 1, 0, 9, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, -1, 0, 150, 0, 8, 0, 1, 1, 0, -1, 0, 0, 0]
    },
    {
      formId: 2,
      name: "飛翔の武神・真田幸村",
      stats: [1700, 5, 75, 2250, 0, 170, 2050, 900, 0, 320, 0, 0, 1, 1, 0, 9, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, -1, 0, 225, 0, 8, 0, 1, 1, 0, -1, 0, 0, 0]
    }
    ],
    rarity: {
      id: 4,
      name: "超激レア",
      maxLevels: [60, 70]
    },
    levelRates: [20, 20, 20, 20, 20, 20, 10, 10, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
  },
  auxiliaryData: {
    names: ["真田幸村", "武神・真田幸村", "飛翔の武神・真田幸村"],
    talents: {
      hasTalents: true,
      hasUltra: false,
      talentList: [
      {
        id: 10,
        name: "攻撃力アップ",
        type: "normal" as const,
        effect: "AP+14%/Lv Max+50% HP≦40% ->114,750 ->68,850",
        npCost: 235,
        isTotal: true
      },
      {
        id: 19,
        name: "動きを止める耐性",
        type: "normal" as const,
        effect: "+16%/Lv Max70%",
        npCost: 175,
        isTotal: true
      },
      {
        id: 20,
        name: "動きを遅くする耐性",
        type: "normal" as const,
        effect: "+16%/Lv Max70%",
        npCost: 175,
        isTotal: true
      },
      {
        id: 32,
        name: "基本体力アップ",
        type: "normal" as const,
        effect: "+2%/Lv Max+20%",
        npCost: 175,
        isTotal: true
      },
      {
        id: 31,
        name: "基本攻撃力アップ",
        type: "normal" as const,
        effect: "+2%/Lv Max+20%",
        npCost: 175,
        isTotal: true
      }
      ]
    }
  }
} as const;

export default unit071Data;

